In [1]:
import numpy as np #algebre linéaire
import matplotlib.pyplot as plt #plot

In [2]:
from sklearn.datasets import fetch_mldata
from sklearn import linear_model

In [3]:
mnist = fetch_mldata('MNIST original')

In [1]:
Xtrain = mnist.data
Ytrain = mnist.target
Xtrain = Xtrain[:50]
#m=nombre d'échantillons , n = Variables
m,n=Xtrain.shape

#définition de la distance
def distance_euclidienne(X,Y):
    return math.sqrt(((X-Y)**2).sum())

#Initialisation de la matrice des distances entre les points (i,j)
Matrix = np.ones([m,m])
print Matrix

#Calcul des distances
for i in range(m):
    for j in range(m):
        Matrix[i,j] = distance_euclidienne(Xtrain[i,:],Xtrain[j,:])
print Matrix
#Définition du nombre de voisin
nbr_voisin = 3       
K = nbr_voisin

#Initialisation de la matrice des voisins
Voisin = np.random.randn(m,3)

def get_K_min_index(K,A,B):
    for i in range(A.shape[0]):
        index_min = np.argmin(A[i,:])
        index_max = np.argmax(A[i,:])
        if index_min == i:
            A[i,index_min] = A[i,index_max]
        for j in range(3):
            """trouver les voisins les 
            plus proche de chaque points"""
            index_min = np.argmin(A[i,:])
            index_max = np.argmax(A[i,:])
            B[i,j] = index_min
            A[i,index_min] = A[i,index_max]

#Création de la matrice des voisin : Voisin[i,:] = K voisins --> K nombre
get_K_min_index(K,Matrix,Voisin)

print("LISTE VOISIN")
print Voisin

#Calcul des poids des voisins
"""Pour chaque point"""
for i in range(m):
    """trouver les alpha(i,j)"""
    print ('training point'+str(i) )
    index = Voisin[i,:].astype(int)
    reg = linear_model.LinearRegression(fit_intercept=False)
    Xtrain_i = Xtrain[i].reshape(784,1)
    Xtrain_i =Xtrain_i
    #Voisin[i,:] correspond aux K plus proches voisins du point en considération (i)
    reg.fit(Xtrain[index].T,Xtrain_i)
    Alphas = reg.coef_
    """trouver les alpha(i,j)"""
    p=0
    for j in range(m):
        if j in Voisin[i,:]:
            Matrix[i,j]=Alphas[0,p]
            p = p+1
        else:
            Matrix[i,j]=0
#trouver les yi dans R2

U = (np.eye(Matrix.shape)-Matrix).T
U = U.dot(np.eye(Matrix.shape)-Matrix)

NameError: name 'mnist' is not defined

In [12]:
M = (np.eye(50)-Matrix).T
M = M.dot(np.eye(50)-Matrix)
print np.linalg.eig(M)

(array([  5.22550996e+00,   3.73925211e+00,   3.63793885e+00,
         3.45331161e+00,   3.12575748e+00,   3.04480109e+00,
         2.91907591e+00,   2.80177771e+00,   2.59295021e+00,
         2.43212520e+00,   2.26339847e+00,   2.21581570e+00,
         2.08555288e+00,   1.84494786e+00,   1.81631417e+00,
         1.69635367e+00,   1.59359699e+00,   7.70623965e-04,
         2.78117278e-02,   6.13530578e-02,   1.53043573e+00,
         1.46352124e-01,   1.87734950e-01,   2.22962379e-01,
         2.50109595e-01,   2.72757090e-01,   3.16946748e-01,
         3.68012679e-01,   1.43854455e+00,   4.54824623e-01,
         5.17223935e-01,   5.35555551e-01,   5.67529161e-01,
         1.35903505e+00,   6.39688381e-01,   6.61304435e-01,
         1.30469772e+00,   1.25760776e+00,   7.56998948e-01,
         8.13240660e-01,   8.64549829e-01,   9.22002802e-01,
         1.13021738e+00,   1.10122976e+00,   1.06060429e+00,
         9.76758367e-01,   1.03518805e+00,   9.96473839e-01,
         1.01301960e+00

In [35]:
A = np.random.randn(6,6)
Voisin = np.random.randn(6,3)

def get_K_min_index(K,A):
    for i in A.shape[0]:
        index_min = np.argmin(A[i,:])
        index_max = np.argmax(A[i,:])
        if index_min == i:
            A[i,index_min] = A[i,index_max]
        for j in range(3):
            """trouver les voisins les 
            plus proche de chaque points"""
            index_min = np.argmin(A[i,:])
            index_max = np.argmax(A[i,:])
            Voisin[i,j] = index_min
            A[i,index_min] = A[i,index_max]

print A
print Voisin

[[-0.89763785  1.11030505  1.82482722  1.84782496 -0.08291643  0.0605327 ]
 [ 1.42697155  0.34247275 -0.16800703 -0.07009718 -1.28460311  0.69030019]
 [-0.54950672  0.79057535  0.88756913 -0.71420096  0.47623207  0.77296635]
 [ 0.82876728 -0.52324686 -3.39976424  0.66517669 -0.36537225 -0.17882518]
 [-0.16103582 -1.62444483 -1.48255554  0.2320589   0.0810082  -0.42194881]
 [ 0.25959496  0.72860097  0.03971838 -1.20687319 -0.80069002 -0.57065759]]
[[ 1.84782496  1.84782496  1.82482722  1.84782496  1.84782496  1.84782496]
 [ 1.42697155  0.34247275  1.42697155  1.42697155  1.42697155  0.69030019]
 [ 0.88756913  0.79057535  0.88756913  0.88756913  0.88756913  0.77296635]
 [ 0.82876728  0.82876728  0.82876728  0.66517669  0.82876728 -0.17882518]
 [-0.16103582  0.2320589   0.2320589   0.2320589   0.0810082   0.2320589 ]
 [ 0.25959496  0.72860097  0.03971838  0.72860097  0.72860097  0.72860097]]
[[ 4.  5.  1.]
 [ 4.  2.  3.]
 [ 3.  0.  4.]
 [ 2.  1.  4.]
 [ 1.  2.  5.]
 [ 3.  4.  5.]]


In [39]:
Xtrain = mnist.data
Ytrain = mnist.target
Xtrain[[1,2,3]]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [75]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit ([[0, 0], [1, 1], [2, 2]], [0, 1, 2])
print [[0, 0], [1, 1], [2, 2]]
reg.coef_


AttributeError: 'list' object has no attribute 'shape'