In [1]:
import numpy as np

def loadMovieLens():

  # Get movie titles
  movies={}
  for line in open('u.item'):
    (id,title)=line.split('|')[0:2]
    movies[id]=title

  # Load data
  prefs={}
  for line in open('u.data'):
    (user,movieid,rating,ts)=line.split('\t')
    prefs.setdefault(user,{})
    prefs[user][movies[movieid]]=float(rating)
  return prefs


In [4]:
data = loadMovieLens()

In [14]:
len(data.keys())

943

In [7]:
import pandas as pd

In [9]:
df = pd.DataFrame(data)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1664 entries, 'Til There Was You (1997) to � k�ldum klaka (Cold Fever) (1994)
Columns: 943 entries, 1 to 99
dtypes: float64(943)
memory usage: 12.0+ MB


In [16]:
df.head()

1   10  100  101  102  103  104  105  106  107  \
'Til There Was You (1997)  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1-900 (1994)               NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
101 Dalmatians (1996)      2.0  NaN  NaN  3.0  NaN  NaN  NaN  NaN  NaN  NaN   
12 Angry Men (1957)        5.0  5.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
187 (1997)                 NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN   

                          ...   94  940  941  942  943   95  96  97  98  99  
'Til There Was You (1997) ...  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN NaN NaN  
1-900 (1994)              ...  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN NaN NaN  
101 Dalmatians (1996)     ...  3.0  NaN  NaN  NaN  NaN  NaN NaN NaN NaN NaN  
12 Angry Men (1957)       ...  NaN  NaN  NaN  NaN  NaN  5.0 NaN NaN NaN NaN  
187 (1997)                ...  NaN  NaN  NaN  NaN  NaN  NaN NaN NaN NaN NaN  

[5 rows x 943 columns]

In [17]:
datas = np.array(df)

In [62]:
datas.shape

(1664L, 943L)

In [29]:
Mask = df.fillna(0)

In [30]:
Mask = Mask.values

Mask = np.where(Mask>0,1,0)

In [169]:
R = datas
C = Mask
R
numberOfItem, numberOfUser = datas.shape
sizeFeature = 3
P = np.random.randn(sizeFeature,numberOfUser)
Q = np.random.randn(sizeFeature,numberOfItem)
print numberOfItem

1664


In [175]:
def loss(R,P,Q,lamb):
    C = get_mask_rating(R)
    s = P.T.dot(Q).T*C
    e = R*C
    res = np.square(np.nan_to_num(e-s))
    res2 = np.trace(P.dot(P.T))**2 + np.trace(Q.dot(Q.T))**2
    loss = np.sum(res) + lamb*res2
    return loss

def get_mask_rating(R):
    Mask = np.where(R>0,1,0)
    return Mask


def descente_de_gradient(It,pas,R,P,Q,lamb):
    nbrItem , nbrUser = R.shape
    idx_matrix_ratings = np.where(np.isfinite(R))
    nombre_index = idx_matrix_ratings[0].shape[0]
    Loss = {}
    i=0
    while i < It:
        idx = np.random.randint(0, nombre_index-1, 1)
        idx_user = idx_matrix_ratings[1][idx]
        idx_item = idx_matrix_ratings[0][idx]
        roU_I = R[idx_item,idx_user] - (P[:,idx_user].T.dot(Q[:,idx_item]))
        
        P[:,idx_user] = (1-lamb*pas)*P[:,idx_user]- pas*Q[:,idx_item]*roU_I
        
        Q[:,idx_item] = (1-lamb*pas)*Q[:,idx_item]- pas*P[:,idx_user]*roU_I
        Loss[i] = loss(R,P,Q,lamb)
        print Loss[i]
        
        i += 1
    plt.figure()
    plt.plot(Loss)
    plt.show()
    Matrix_rating = P
    return Loss,Matrix_rating

Loss, Matrix = descente_de_gradient(1000,0.01,R,P,Q,0.5)

20616130.9785
20615704.0732
20616038.4083
20615056.7872
20614389.1086
20613496.1318
20615078.8103
20616174.9772
20615741.8559
20615454.9685
20615556.1946
20615234.1024
20614151.4219
20615335.1782
20616521.2706
20618061.8091
20617831.3608
20626077.0505
20626135.209
20625660.7396
20626219.2136
20625308.4723
20624384.5428
20623871.6879
20623557.6326
20622487.3838
20625156.0257
20625021.0224
20624772.8473
20625537.293
20625249.5039
20624263.1501
20623868.0763
20623411.0389
20623452.3973
20625708.5745
20624723.9874
20625615.3294
20625293.2384
20624919.7682
20627172.0105
20628277.6212
20627197.6734
20627795.7078
20627672.4866
20628780.0756
20628361.8738
20627842.9182
20626381.1341
20628408.5954
20628191.6942
20626849.4049
20627754.0097
20627356.0438
20627244.8251
20626467.0843
20627177.0981
20626859.5516
20625935.4958
20626154.2449
20628934.6815
20629994.0343
20629653.8541
20628713.3558
20628470.2998
20628108.6689
20629278.2059
20631071.5426
20630313.7239
20629631.5999
20628586.3396
20628726

KeyboardInterrupt: 

In [172]:
import matplotlib.pyplot as plt
plt.plot(Loss)

NameError: name 'Loss' is not defined

In [71]:
s.shape

(1664L, 943L)

In [75]:
e = R*C

In [76]:
e.shape

(1664L, 943L)

In [78]:
np.square(e-s)

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [  1.,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [  1.,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [79]:
e-s

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ -1.,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [  1.,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

In [84]:
np.sum(np.square(np.nan_to_num(e-s)))

154294.0

In [85]:
np.nan_to_num(e-s)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [-1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [105]:
h = np.array([range(5)])

In [107]:
m = np.array([range(5)]).T

In [109]:
h.dot(m)

array([[30]])