In [73]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.base import BaseEstimator,ClassifierMixin
from sklearn import cross_validation
from sklearn.metrics import accuracy_score

In [87]:
def pas_SGD_regularization_L1(X,Y,lamb,epsilone,grad):
    for i in range(X.shape[1]):
        idx = np.random.randint(X.shape[0])
        error = Y[idx]-X[idx,:].dot(grad)
        print error,grad
        grad1 = grad + (2*epsilone*X[idx,:]*error) + lamb*np.sign(grad)
        grad = np.where(grad1*grad<0,0,grad1)
    return grad
    

In [88]:
class RegularisationL1(BaseEstimator,ClassifierMixin):
    def __init__(self,lamb,eps,iteration):
        self.lamb = lamb
        self.eps = eps
        self.I = iteration
        
    def fit(self,X,Y):
        #l correspond aux nombres de données dans notre ensemble d'apprentissage
        #n correspond aux nombres de variables de chaques vecteurs
        l , n = X.shape
        
        #initialisation gradient par une normale centrée réduite
        grad = np.random.randn(n,1)
        
        #descente de gradient
        for epoch in range(self.I):
            
            #Calcul de Ltheta pour controle
            Ltheta = (1/float(l))*((Y-X.dot(grad))**2).sum()+self.lamb*((abs(grad)).sum())
            print Ltheta
            grad = pas_SGD_regularization_L1(X,Y,self.lamb,self.eps,grad)    
            
        #récupération des paramètres
        self.coef=grad
        return self

    def predict(self,X):
        l=X.shape[0]
        result=np.zeros([l,1])
        j=0
        for i in X:
            result[j,0]=i.dot(self.coef)
            if (result[j,0]>0):
                result[j,0]=1
            elif (result[j,0]<0):
                result[j,0]=-1
            else:
                result[j,0]=np.random.randint(2)
                if result[j,0]==0:
                        result[j,0]=-1
            j=j+1  
        return result
        
    

In [89]:
from sklearn import datasets
iris = datasets.load_iris()
X=iris.data
Y=iris.target
Y=np.where(Y==2,1,Y)
Y=np.where(Y==0,-1,Y)
Y = Y.reshape(150,1)




In [90]:
a=RegularisationL1(lamb=0,eps=0.0001,iteration=10)

In [91]:
a.fit(X,Y)

160.811833377
[ 14.54679452] [[-1.20357744]
 [-0.5743309 ]
 [-0.84883438]
 [ 0.02319382]]
[ 9.07371692  9.19102227  9.14866201  9.24641647] [[-1.18408473 -1.19455843 -1.19077626 -1.19950434]
 [-0.55483819 -0.56531188 -0.56152972 -0.57025779]
 [-0.82934167 -0.83981536 -0.8360332  -0.84476127]
 [ 0.04268652  0.03221283  0.035995    0.02726692]]
[ 7.96302198  8.10221511  8.11623983  8.2238896 ] [[-1.17355922 -1.18720561 -1.18858058 -1.19913448]
 [-0.54431268 -0.55795907 -0.55933404 -0.56988794]
 [-0.81881616 -0.83246255 -0.83383752 -0.84439142]
 [ 0.05321203  0.03956565  0.03819068  0.02763678]]
[ 12.38135798  12.60221937  12.67132365  12.84628851] [[-1.1655962  -1.18137201 -1.18630803 -1.19880552]
 [-0.53634966 -0.55212547 -0.55706149 -0.56955898]
 [-0.81085314 -0.82662895 -0.83156497 -0.84406246]
 [ 0.06117506  0.04539924  0.04046322  0.02796573]]
601.906136297
[ 7.09812022  7.30568728  7.32549182  7.50924247] [[-1.15172908 -1.17381068 -1.17591755 -1.19546549]
 [-0.52248254 -0.54456414 

RegularisationL1(eps=0.0001, iteration=None, lamb=0)

In [65]:
data = datasets.load_svmlight_file('/home/gozuslayer/Dac/Dac/FDMS/Semaine2/a5a')

In [66]:
x = data[0].todense()
y = data[1]

In [67]:
ba=RegularisationL1(lamb=0,eps=0.0001,iteration=10)
ba.fit(x,y)

303181432.387


ValueError: shapes (1,122) and (1,1) not aligned: 122 (dim 1) != 1 (dim 0)

In [180]:
grad = np.random.randn(4,1)
print grad,x[1],float(x[0].dot(grad)),x[1]*(x[0].dot(grad))

 [[ 1.19801943]
 [-0.61260179]
 [ 0.0578844 ]
 ..., 
 [ 1.9735774 ]
 [-0.34027781]
 [-0.09310071]] [[ 1.10946   0.786453  0.44556  ...,  1.09401  -0.492141 -1.55408 ]] 17.241613329

ValueError: shapes (1,2000) and (1,1) not aligned: 2000 (dim 1) != 1 (dim 0)

In [44]:
A =  np.random.randn(4,1)
B =  np.random.randn(4,1)
np.where(A*B>0,10,A*B)

array([[ 10.        ],
       [ -0.20721188],
       [ -1.64223685],
       [ 10.        ]])

In [45]:
A

array([[ 0.24634432],
       [ 0.3010444 ],
       [ 0.81483434],
       [ 0.81357771]])

In [46]:
B

array([[ 1.38904729],
       [-0.68831005],
       [-2.01542421],
       [ 1.39877102]])

In [93]:
A.dot(B.T)

array([[ 0.34218391, -0.16956127, -0.49648831,  0.3445793 ],
       [ 0.4181649 , -0.20721188, -0.60673217,  0.42109218],
       [ 1.13184343, -0.56085866, -1.64223685,  1.13976666],
       [ 1.13009791, -0.55999371, -1.63970421,  1.13800892]])

In [3]:
import numpy as np
A = np.random.randn(5,1)

In [4]:
A*A

array([[ 0.26115472],
       [ 0.2678391 ],
       [ 0.0797169 ],
       [ 3.82699263],
       [ 1.62671687]])